name: Deploy to GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm
        run: npm i -g npm@latest
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      # - name: Add CNAME file
      #   run: touch ./out/CNAME
      # - name: Update CNAME
      #   run: echo {catchy-domain.name} >> ./out/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out